name: qaryenv
channels:
  # anaconda required for
  # - anaconda  # bad idea: https://github.com/conda/conda/issues/9462
  # - spacy
  - huggingface
  - pytorch
  - conda-forge
  - defaults  # top priority: https://docs.conda.io/projects/conda/en/latest/user==guide/tasks/manage==channels.html#managing==channels

dependencies:
  - asciidoctor=2.0.16
  - beautifulsoup4=4.10.0
  - boto3=1.21.25
  - configargparse=1.5.3
  - django=4.0.3
  # - elasticsearch=8.1.1
  - ffmpeg=4.3
  - gitpython=3.1.27
  - graphviz=2.48.0
  - html2text=2020.1.16
  - html5lib=1.1
  - huggingface_hub
  # jupyter causes many conflicts
  - jupyter_console=6.4.3  # 5.2.0 6.0.0 6.1.0 6.2.0 **6.3.0** 6.4.0 6.4.3
  - matplotlib-base=3.4.2
  # - networkx=2.7.1
  - nltk=3.6.7
  - numpy=1.21.1
  - pandas=1.3.1
  # - Pillow=9.0.1
  - pip
  - pynndescent=0.5.6
  - pre-commit=2.17.0
  - protobuf=3.16.0
  - pytest-cov
  - python=3.9.7
  - pytorch-cpu=1.9.0
  - qtpy=2.0.1
  - regex=2021.8.3
  - ruby=2.6.6
  - scikit-learn=0.24.2
  # - scikit_image-0.19.2
  - scipy=1.7.0
  - seaborn=0.11.2
  - sentence-transformers=2.1.0
  - sentencepiece=0.1.95
  - spacy=3.1.1
  - spacy-legacy=3.0.8
  - sphinx=4.4.0
  - torchtext=0.10.0
  - torchvision=0.2.2
  - transformers=4.11.3
  # - urllib3<1.27,>=1.25.4
  - wikipedia  # 1.4.0
  - xmltodict=0.12.0
  - pip:
    - wikipedia @ https://gitlab.com/tangibleai/Wikipedia/-/archive/1.4.1/Wikipedia-1.4.1.zip
    # - edit-distance==1.0.4

