git mv "Chapter 07 -- Finding Kernels of Knowledge in Text with Convolutional Neural Networks (CNNs).adoc" "Chapter-07_Finding-Kernels-of-Knowledge-in-Text-with-Convolutional-Neural-Networks-CNNs.adoc"
git mv "Chapter 13 -- Getting creative (finding and generating text summaries and paraphrases).adoc" "Chapter-13_Getting-creative-finding-and-generating-text-summaries-and-paraphrases.adoc"
git mv "Chapter 06 -- Reasoning with word embeddings (word vectors).adoc" "Chapter-06_Reasoning-with-word-embeddings-word-vectors.adoc"
git mv "Chapter 04 -- Finding Meaning in Word Counts (Semantic Analysis).adoc" "Chapter-04_Finding-Meaning-in-Word-Counts-Semantic-Analysis.adoc"
git mv "Chapter 00 -- Preface.adoc" "Chapter-00_Preface.adoc"
git mv "Chapter 14 -- Scaling up (optimization, parallelization, and batch processing).adoc" "Chapter-14_Scaling-up-optimization,-parallelization,-and-batch-processing.adoc"
git mv "Chapter 00 -- Acknowledgments.adoc" "Chapter-00_Acknowledgments.adoc"
git mv "Chapter 05 -- Word Brain (artificial neural networks for NLP).adoc" "Chapter-05_Word-Brain-artificial-neural-networks-for-NLP.adoc"
git mv "Chapter 12 -- Getting chatty (dialog engines).adoc" "Chapter-12_Getting-chatty-dialog-engines.adoc"
git mv "Chapter 09 -- Stackable deep learning (Transformers).adoc" "Chapter-09_Stackable-deep-learning-Transformers.adoc"
git mv "Chapter 08 -- Reduce, Reuse, Recycle (Recurrent Neural Networks).adoc" "Chapter-08_Reduce,-Reuse,-Recycle-Recurrent-Neural-Networks.adoc"
git mv "Chapter 00 -- Foreword by Arwen Griffioen.adoc" "Chapter-00_Foreword-by-Arwen-Griffioen.adoc"
git mv "Chapter 11 -- Information extraction and logic (semantic parsing).adoc" "Chapter-11_Information-extraction-and-logic-semantic-parsing.adoc"
git mv "Chapter 00 -- About this Book.adoc" "Chapter-00_About-this-Book.adoc"