pip install --upgrade pip
pip install \
    beautifulsoup4 \
    boto3 \
    ConfigArgParse \
    Cython \
    django \
    edit-distance \
    elasticsearch \
    environment \
    gitpython \
    graphviz \
    h5py \
    html5lib \
    html2text \
    jupyter \
    jupyter-console \
    lxml \
    m2r \
    matplotlib \
    meilisearch \
    nltk \
    pillow \
    pronouncing \
    pytest \
    python-slugify \
    rapidfuzz \
    recommonmark \
    scikit-image \
    scipy \
    sentence_transformers \
    transformers \
    tqdm \
    wikipedia \
    pytest \
    pytest-cov \
    pylint \
    pydocstyle \
    pre-commit